---
- hosts: jar
  tasks:
  - name: 引入zabbix的源
    command: rpm -ivh http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm  > /dev/null 2>&1
  
  - name: 安装expect
    yum: name={{ item }} state=present
    with_items:
     - expect
     - zabbix-agent
     - zabbix-get

  - name: 复制文件
    copy: 
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: root
     group: root
    with_items: 
    - { 
        src: "/root/script/out.txt",
        dest: "/root/out.txt"
      }

---
- hosts: jar
  tasks:
  - name: 复制文件
    copy: 
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: root
     group: root
    with_items: 
    - {
        src: "/root/script/out.txt",
        dest: "/root/out.txt"
      }