copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkc03757\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkc03760\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkc03852\WebContent\WEB-INF\lib"

copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA001\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA002\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA004\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA005\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA006\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA007\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA008\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA009\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA011\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA012\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA014\WebContent\WEB-INF\lib"

copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcArtificial\WebContent\WEB-INF\lib"

copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcB001\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcB002\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcB003\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcC001\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcD001\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE001\WebContent\WEB-INF\lib"

copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS001\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS002\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS003\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS004\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS005\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS006\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS007\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS008\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS009\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS010\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS011\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS012\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS013\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS014\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS015\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS016\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS017\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS018\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS019\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS020\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS021\WebContent\WEB-INF\lib"

copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX001\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX002\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX003\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX004\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX005\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX006\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX007\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX008\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX009\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE002\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE003\WebContent\WEB-INF\lib"

copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcSpecial004\WebContent\WEB-INF\lib"
copy /Y "C:\Users\User\Desktop\replace\lib\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcSpecial005\WebContent\WEB-INF\lib"


