copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkc03757"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkc03760"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkc03852"

copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA001"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA002"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA004"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA005"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA006"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA007"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA008"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA009"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA011"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA012"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA014"

copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcArtificial"

copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcB001"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcB002"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcB003"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcC001"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcD001"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE001"

copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS001"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS002"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS003"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS004"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS005"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS006"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS007"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS008"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS009"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS010"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS011"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS012"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS013"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS014"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS015"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS016"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS017"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS018"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS019"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS020"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS021"

copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX001"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX002"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX003"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX004"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX005"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX006"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX007"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX008"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX009"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE002"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE003"

copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcSpecial004"
copy /Y "C:\Users\User\Desktop\replace\classpath\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcSpecial005"


