copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkc03757\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkc03760\src\com\bidizhaobiao\data\crawl\domain"

copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcA001\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcA002\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcA004\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcA005\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcA006\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcA007\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcA008\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcA009\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcA011\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcA012\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcA014\src\com\bidizhaobiao\data\crawl\domain"

copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcArtificial\src\com\bidizhaobiao\data\crawl\domain"

copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcB001\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcB002\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcB003\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcC001\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcD001\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcE001\src\com\bidizhaobiao\data\crawl\domain"

copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS001\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS002\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS003\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS004\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS005\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS006\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS007\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS008\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS009\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS010\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS011\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS012\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS013\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS014\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS015\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS016\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS017\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS018\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS019\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS020\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcDS021\src\com\bidizhaobiao\data\crawl\domain"

copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcQX001\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcQX002\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcQX003\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcQX004\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcQX005\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcQX006\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcQX007\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcQX008\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcQX009\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcE002\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcE003\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcE004\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcE005\src\com\bidizhaobiao\data\crawl\domain"

copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcSpecial004\src\com\bidizhaobiao\data\crawl\domain"
copy /Y "C:\Users\User\Desktop\replace\domain\*" "D:\Workspace\Myeclipse\bxkcSpecial005\src\com\bidizhaobiao\data\crawl\domain"


