copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkc03757\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkc03760\config"

copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA001\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA002\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA011\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA012\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA006\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA007\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA008\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA009\config"

copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcB001\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcB002\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcC001\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcD001\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE001\config"

copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS001\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS002\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS003\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS004\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS005\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS006\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS007\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS008\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS009\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS010\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS011\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS012\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS013\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS014\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS015\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS016\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS017\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS018\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS019\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS020\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS021\config"

copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX001\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX002\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX003\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX004\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX005\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX006\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX007\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX008\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX009\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE002\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE003\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE004\config"
copy /Y "C:\Users\User\Desktop\replace\config\*" "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE005\config"


