del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkc03757\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkc03760\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkc03852\src\com\bonait\dataextract\util"

del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA001\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA002\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA004\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA005\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA006\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA007\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA008\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcA009\src\com\bonait\dataextract\util"

del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcArtificial\src\com\bonait\dataextract\util"

del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcB001\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcB002\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcB003\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcC001\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcD001\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE001\src\com\bonait\dataextract\util"

del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS001\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS002\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS003\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS004\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS005\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS006\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS007\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS008\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS009\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS010\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS011\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS012\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS013\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS014\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS015\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS016\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS017\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS018\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS019\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS020\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcDS021\src\com\bonait\dataextract\util"

del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX001\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX002\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX003\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX004\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX005\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX006\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX007\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcQX008\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcE002\src\com\bonait\dataextract\util"

del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcSpecial004\src\com\bonait\dataextract\util"
del /Q "D:\programming software\MyEclipse 10.6\MyEclipse.10 Documents\bxkcSpecial005\src\com\bonait\dataextract\util"


